### ISSUE TITLE
min algorithm error when there are multiple samples of the same species, but only 1 of them is from the island

### ISSUE THREAD

**Issue by luislvalente** [joshwlambert/DAISIEprep#43]
When running the min algorithm on the Canary Islands dataset, I get this error:

```
island_tbl <- extract_island_species(
  phylod = phylod,
  extraction_method = "min"
)
island_tbl
```
`Error in .local(x, ...) : 0 or 1 tips would remain after subsetting`

This happens in Line 91 of function `extract_multi_tip_species()`

```  
  # subset the multi-tip nonendemic species from the rest of the tree
  multi_tip_species_phylod <- phylobase::subset(
    x = phylod,
    tips.include = species_tips
  )
```
The error occurs to **non-endemic species** that are represented by multiple samples on the tree (two or more tips), but only one of them is a sample from the island, the others are not from the island. If there are multiple samples of the same non-endemic species and two of them are on the island, the code works fine because it can keep a subtree with at least two island tips.

**Comment by joshwlambert** [comment]
This issue has been fixed in pull request #51. It is resolved by making the check in `is_multi_tip_species()` (which is a function called internally to determine if a species has multiple tips) more strict. Before it only checked whether there were multiple tips that formed a monophyletic clade that all shared a genus and species name. Now it also checks whether these have the same endemicity status.

In the case where samples from the mainland are labelled as `"not_present"` and only one sample is from the island then it is not considered a multi-tip species for the purposes of DAISIEprep extraction. 

This resolves the bug encountered above. 

A new vignette is also drafted to outline some of the thinking around this issue and some discussion with @luislvalente on the differents methods empiricists may use to encode the endemicity status of different samples. See the vignette on the website for more details.
